version: '3.8'

services: 
    mysqldb:
        image: mysql:5.7
        container_name: mysqldb
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql
        networks:
            - backend

    backend:
        depends_on:
            - mysqldb
        build: 
            context: ./backend
            args:
                - PORT=$BACKEND_DOCKER_PORT
        image: szekler/my-awesome-blog-backend
        container_name: backend
        restart: unless-stopped
        env_file: ./.env
        ports: 
            - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
        environment:
            - DB_HOST=mysqldb
            - DB_USER=$MYSQLDB_USER
            - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - DB_NAME=$MYSQLDB_DATABASE
            - DB_PORT=$MYSQLDB_DOCKER_PORT

            - CLIENT_ORIGIN=$CLIENT_ORIGIN
            - JWT_SECRET=$JWT_SECRET
            - PORT=$BACKEND_DOCKER_PORT
        networks:
            - backend

    frontend:
        depends_on:
            - backend
        build:
            context: ./frontend
            args:
                - API_BASE_URL=$CLIENT_API_BASE_URL
        image: szekler/my-awesome-blog-frontend
        container_name: frontend
        ports:
            - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT

volumes:
  db:
    
networks:
  backend: