version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    command: npm run dev
