version: '3.8'

services: 
    # mysqldb:
    #     image: mysql:5.7
    #     container_name: mysqldb
    #     restart: unless-stopped
    #     env_file: ./.env
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    #         - MYSQL_DATABASE=$MYSQLDB_DATABASE
    #     ports:
    #         - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    #     volumes:
    #         - db:/var/lib/mysql

    backend:
        # depends_on:
        #     - mysqldb
        build: ./backend
        image: szekler/my-awesome-blog-backend
        container_name: backend
        restart: unless-stopped
        env_file: ./.env
        ports: 
            - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
        environment:
            - DB_HOST=$MYSQLDB_HOST
            - DB_PORT=$MYSQLDB_LOCAL_PORT
            - DB_USER=$MYSQLDB_USER
            - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - DB_NAME=$MYSQLDB_DATABASE

            - CLIENT_ORIGIN=$CLIENT_ORIGIN
            - JWT_SECRET=$JWT_SECRET
            - PORT=$BACKEND_DOCKER_PORT

    frontend:
        depends_on:
            - backend
        build:
            context: ./frontend
            args:
                - API_BASE_URL=$API_BASE_URL:$BACKEND_LOCAL_PORT
        # image: szekler/my-awesome-blog-frontend
        container_name: frontend
        ports:
            - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT

# volumes:
#   db:
