version: '3.8'

services: 
    backend:
        image: szekler/my-awesome-blog-backend
        container_name: backend
        restart: unless-stopped
        env_file: ./.env
        ports: 
            - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
        environment:
            - DB_HOST=$MYSQLDB_HOST
            - DB_USER=$MYSQLDB_USER
            - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - DB_NAME=$MYSQLDB_DATABASE
            - DB_PORT=$MYSQLDB_DOCKER_PORT

            - CLIENT_ORIGIN=$CLIENT_ORIGIN
            - JWT_SECRET=$JWT_SECRET
            - PORT=$BACKEND_DOCKER_PORT

    frontend:
        depends_on:
            - backend
        build:
            context: ./frontend
            args:
                - API_BASE_URL=$API_BASE_URL:$BACKEND_LOCAL_PORT
        image: szekler/my-awesome-blog-frontend
        container_name: frontend
        ports:
            - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT
