name: Deploy on Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
env:
  AZURE_WEBAPP_NAME: my-awesome-blog-backend
  AZURE_WEBAPP_PACKAGE_PATH: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: npm ci --omit=dev
        working-directory: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:    
      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.BLOG_AZURE_PUBLISH_PROFILE }}
          slot-name: production
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
