name: Deploy frontend on Azure

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  API_BASE_URL: "https://my-awesome-blog-backend.azurewebsites.net"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      
      - name: Set api base url
        run: echo VITE_API_BASE_URL=$API_BASE_URL > ./frontend/.env

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_MUSHROOM_0E7700E10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./frontend"
          output_location: "dist"

